curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
curl -i -d '{"timestamp": 4000, "weather": [{"dfn": 0, "weather": "sunny"}, {"dfn": 1, "weather": "rainy"}]}' -H 'Content-Type: application/json' http://localhost:5000/metrology
